"""
cv/prep_sdnet.py — build a YOLO-seg crack dataset (single class 'crack') in
data/cv/yolo, ALWAYS producing something usable at demo time.

Priority:
  1. --dataset ultralytics (default): download Ultralytics' crack-seg dataset
     (~91.6 MB, https://github.com/ultralytics/assets/releases/download/v0.0.0/crack-seg.zip).
     It ships in YOLO-seg format already -> copied/merged into <out>/images|labels.
  2. --dataset sdnet --sdnet-path <dir>: point at a local SDNET2018 download
     (IEEE DataPort slug sdnet2018-concrete-crack-image-dataset-machine-learning-applications).
     SDNET2018 is classification-only, so approximate crack segmentation labels
     are synthesised from edges/contours (clearly documented as approximate).
  3. Any download failure -> synthetic crack images+masks generated locally so
     training code stays exercisable offline.

Output layout (YOLO-seg):
    <out>/images/{train,val}/*.jpg
    <out>/labels/{train,val}/*.txt      # "0 x1 y1 x2 y2 ..." normalized polygon
    <out>/data.yaml                     # path / train / val / names: {0: crack}

Usage:
    python models/cv/prep_sdnet.py --out data/cv/yolo --dataset ultralytics
    python models/cv/prep_sdnet.py --out data/cv/yolo --dataset synthetic
"""
from __future__ import annotations

import argparse
import shutil
import sys
import urllib.request
import zipfile
from pathlib import Path

import numpy as np
import cv2  # noqa: F401 (imported for side effects / presence check)

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUT = REPO_ROOT / "data" / "cv" / "yolo"

CRACK_SEG_URL = ("https://github.com/ultralytics/assets/releases/download/v0.0.0/crack-seg.zip")
SDNET_PAGE = ("https://ieee-dataport.org/open-access/"
              "sdnet2018-concrete-crack-image-dataset-machine-learning-applications")


# ---------------------------------------------------------------------------
# data.yaml
# ---------------------------------------------------------------------------
def write_data_yaml(out: Path, names: list[str] | None = None) -> Path:
    names = names or ["crack"]
    out.mkdir(parents=True, exist_ok=True)
    lines = [
        f"# YOLO-seg dataset (single class). Generated by models/cv/prep_sdnet.py",
        f"path: {out.resolve().as_posix()}",
        "train: images/train",
        "val: images/val",
        "names:",
    ]
    for i, n in enumerate(names):
        lines.append(f"  {i}: {n}")
    yaml = out / "data.yaml"
    yaml.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return yaml


# ---------------------------------------------------------------------------
# Synthetic crack set (offline-safe, deterministic)
# ---------------------------------------------------------------------------
def _concrete_base(size: int, rng: np.random.Generator) -> np.ndarray:
    base = np.full((size, size), float(rng.uniform(125, 165)), dtype=np.float32)
    base += rng.standard_normal((size, size)) * 8.0
    for _ in range(rng.integers(6, 12)):
        y0, x0 = rng.integers(0, size, 2)
        r = int(rng.integers(2, 6))
        cv2.circle(base, (int(x0), int(y0)), r, float(rng.uniform(-18, 18)), -1)
    base = cv2.GaussianBlur(base, (3, 3), 0)
    return base


def _random_crack_polyline(size: int, rng: np.random.Generator) -> np.ndarray:
    """A jagged crack polyline across the image (points in (x,y) order)."""
    x = float(rng.uniform(0.05, 0.25)) * size
    y = float(rng.uniform(0.1, 0.9)) * size
    pts = [(int(x), int(y))]
    steps = int(rng.integers(4, 8))
    for _ in range(steps):
        x += rng.uniform(0.08, 0.3) * size
        y += rng.uniform(-0.3, 0.3) * size
        pts.append((int(min(max(x, 2), size - 3)), int(min(max(y, 2), size - 3))))
    return np.array(pts, dtype=np.int32).reshape(-1, 1, 2)


def make_crack_image(size: int = 256, seed: int = 0) -> tuple[np.ndarray, np.ndarray]:
    """Return (img_bgr_uint8, binary_mask) of a synthetic concrete crack."""
    rng = np.random.default_rng(seed)
    img = _concrete_base(size, rng)
    mask = np.zeros((size, size), dtype=np.uint8)
    poly = _random_crack_polyline(size, rng)
    thick = int(rng.integers(2, 5))
    cv2.polylines(mask, [poly], False, 255, thickness=thick)
    # a couple of short branches
    for _ in range(rng.integers(0, 3)):
        bp = _random_crack_polyline(size, rng)[:3]
        cv2.polylines(mask, [bp], False, 160, thickness=max(1, thick - 1))
    mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, np.ones((3, 3), np.uint8))
    dark = np.zeros((size, size), dtype=np.uint8)
    cv2.polylines(dark, [poly], False, 255, thickness=thick)
    crack_shade = np.clip(img - 45, 0, 255)
    img = np.where(dark > 0, crack_shade, img)   # dark is 2D -> keeps img 2D
    img = cv2.GaussianBlur(img, (3, 3), 0)
    img = np.clip(img, 0, 255).astype(np.uint8)
    return cv2.cvtColor(img, cv2.COLOR_GRAY2BGR), mask


def _mask_to_yolo_label(mask: np.ndarray) -> str:
    """Largest-contour polygon of a mask -> YOLO-seg text line (class 0)."""
    h, w = mask.shape
    contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    if not contours:
        return ""
    c = max(contours, key=cv2.contourArea)
    if cv2.contourArea(c) < 20:
        return ""
    peri = cv2.arcLength(c, True)
    approx = cv2.approxPolyDP(c, max(1.0, 0.004 * peri), True).reshape(-1, 2).astype(np.float32)
    if len(approx) < 3:
        return ""
    return "0 " + " ".join(f"{x / w:.6f} {y / h:.6f}" for x, y in approx)


def generate_synthetic_crack_dataset(out: Path, n_train: int = 40, n_val: int = 12,
                                     img_size: int = 256, seed: int = 0) -> Path:
    """Generate a small synthetic crack YOLO-seg set (offline-safe)."""
    out = Path(out)
    for split in ("train", "val"):
        (out / "images" / split).mkdir(parents=True, exist_ok=True)
        (out / "labels" / split).mkdir(parents=True, exist_ok=True)
    count = {"train": 0, "val": 0}
    for split, n in (("train", n_train), ("val", n_val)):
        for i in range(n):
            img, mask = make_crack_image(img_size, seed=int(seed) * 1000 + (10000 if split == "val" else 0) + i)
            if i % 7 == 6:  # ~15% negatives (no crack -> no label file)
                mask = np.zeros_like(mask)
            fname = f"{split}_{i:03d}.jpg"
            cv2.imwrite(str(out / "images" / split / fname), img)
            lbl = _mask_to_yolo_label(mask)
            if lbl:
                (out / "labels" / split / f"{split}_{i:03d}.txt").write_text(lbl + "\n", encoding="utf-8")
            count[split] += 1
    yaml = write_data_yaml(out)
    print(f"  [synthetic] wrote {count} images -> {out}")
    print(f"  [synthetic] data.yaml: {yaml}")
    return yaml


# ---------------------------------------------------------------------------
# Ultralytics crack-seg download + convert
# ---------------------------------------------------------------------------
def download(url: str, dest: Path, timeout: int = 240) -> Path:
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0 SHM-Bridges"})
    dest.parent.mkdir(parents=True, exist_ok=True)
    with urllib.request.urlopen(req, timeout=timeout) as resp, open(dest, "wb") as fh:
        shutil.copyfileobj(resp, fh, length=1 << 20)
    return dest


def convert_ultralytics_crack_seg(zip_path: Path, out: Path) -> Path:
    """Extract crack-seg.zip (already YOLO-seg) and merge into <out>."""
    with zipfile.ZipFile(zip_path) as zf:
        zf.extractall(out.parent)
    root = out.parent
    img_dirs = sorted((root / "crack-seg").glob("images/*")) if (root / "crack-seg").exists() else sorted(root.glob("*/images/*"))
    if not img_dirs:
        raise FileNotFoundError(f"no images/* found in extracted crack-seg at {root}")
    for img_dir in img_dirs:
        src_split = img_dir.name
        split = "val" if src_split in ("test", "valid") else src_split
        lab_dir = img_dir.parent.parent / "labels" / src_split
        (out / "images" / split).mkdir(parents=True, exist_ok=True)
        (out / "labels" / split).mkdir(parents=True, exist_ok=True)
        for img in img_dir.glob("*"):
            if img.suffix.lower() not in (".jpg", ".jpeg", ".png"):
                continue
            shutil.copy(img, out / "images" / split / img.name)
            lbl = lab_dir / (img.stem + ".txt")
            if lbl.exists():
                shutil.copy(lbl, out / "labels" / split / lbl.name)
    yaml = write_data_yaml(out)
    n_img = sum(1 for _ in (out / "images").glob("*/*"))
    print(f"  [ultralytics] copied {n_img} images into {out}")
    print(f"  [ultralytics] data.yaml: {yaml}")
    return yaml


def convert_sdnet(sdnet_root: Path, out: Path, val_frac: float = 0.2) -> Path:
    """SDNET2018 (classification-only) -> approximate YOLO-seg crack labels."""
    import re
    out = Path(out)
    for split in ("train", "val"):
        (out / "images" / split).mkdir(parents=True, exist_ok=True)
        (out / "labels" / split).mkdir(parents=True, exist_ok=True)
    # SDNET dirs: <root>/Crack/*.png and <root>/Uncracked/*.png (or nested)
    cracked = []
    for pat in ("**/Cracked/*", "**/Crack/*", "**/cracked/*", "**/crack/*"):
        cracked += sorted(Path(sdnet_root).glob(pat))
    cracked = [p for p in cracked if p.suffix.lower() in (".png", ".jpg", ".jpeg")]
    if not cracked:
        raise FileNotFoundError(f"no SDNET cracked images under {sdnet_root} "
                                f"(expected <root>/Crack/*.png). Download from {SDNET_PAGE}.")
    rng = np.random.default_rng(0)
    for i, img_path in enumerate(cracked):
        img = cv2.imread(str(img_path), cv2.IMREAD_GRAYSCALE)
        if img is None:
            continue
        img = cv2.resize(img, (256, 256))
        img_bgr = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)
        mask = _approx_crack_mask(img, rng)
        split = "val" if i % max(1, round(1 / val_frac)) == 0 else "train"
        fname = f"sdnet_{i:05d}.jpg"
        cv2.imwrite(str(out / "images" / split / fname), img_bgr)
        lbl = _mask_to_yolo_label(mask)
        if lbl:
            (out / "labels" / split / f"{fname.rsplit('.', 1)[0]}.txt").write_text(lbl + "\n", encoding="utf-8")
    yaml = write_data_yaml(out)
    print(f"  [sdnet] converted {len(cracked)} images -> {out} (approximate masks)")
    return yaml


def _approx_crack_mask(gray: np.ndarray, rng: np.random.Generator) -> np.ndarray:
    """Rough crack segmentation via Canny + morphological closing (heuristic)."""
    blur = cv2.GaussianBlur(gray, (5, 5), 0)
    edges = cv2.Canny(blur, 40, 110)
    kernel = np.ones((3, 3), np.uint8)
    mask = cv2.dilate(edges, kernel, iterations=2)
    mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, np.ones((5, 5), np.uint8))
    return mask


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------
def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Build a YOLO-seg crack dataset")
    ap.add_argument("--out", default=str(DEFAULT_OUT), help="output dir (default data/cv/yolo)")
    ap.add_argument("--dataset", choices=["ultralytics", "sdnet", "synthetic"], default="ultralytics")
    ap.add_argument("--sdnet-path", default=None, help="local SDNET2018 root dir")
    ap.add_argument("--timeout", type=int, default=240, help="download timeout (s)")
    ap.add_argument("--seed", type=int, default=0)
    args = ap.parse_args(argv)

    out = Path(args.out)
    try:
        if args.dataset == "ultralytics":
            zip_path = out.parent / "crack-seg.zip"
            if not zip_path.exists():
                print(f"  [net] downloading {CRACK_SEG_URL} ({zip_path}) ...")
                download(CRACK_SEG_URL, zip_path, timeout=args.timeout)
            return 0 if convert_ultralytics_crack_seg(zip_path, out) else 1
        if args.dataset == "sdnet":
            if not args.sdnet_path:
                print(f"ERROR: --sdnet-path required for SDNET2018. Manual download page:\n"
                      f"  {SDNET_PAGE}\n"
                      f"Rerun with --dataset synthetic for an offline dataset.",
                      file=sys.stderr)
                return 1
            return 0 if convert_sdnet(Path(args.sdnet_path), out) else 1
        if args.dataset == "synthetic":
            generate_synthetic_crack_dataset(out, seed=args.seed)
            return 0
    except Exception as exc:
        print(f"  [prep] WARNING: dataset path failed ({exc}). "
              f"Falling back to a synthetic crack set so training stays exercisable.")
    generate_synthetic_crack_dataset(out, seed=args.seed)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
