"""
cv/prep_negatives.py — add crack-free NEGATIVE images to the yolo9k subset so
the segmenter learns "plain concrete = no crack".

    python models/cv/prep_negatives.py

Why: CrackSeg9k contains only images that have a crack, so a model trained on
it learns "every concrete image contains a crack" and draws high-confidence
masks on clean concrete (90% FP in verification). The fix is to train on a
mix of cracked positives and crack-free negatives.

Negative source: crack-free 256x256 quadrants CROPPED from the CC0 yolo9k
images themselves (regions where the crack mask covers <0.5% of the patch).
This keeps the training data 100% CC0 (no SDNET/dacl10k in the weights) and
stays in-distribution (same concrete surfaces as the positives).

Output: data/cv/yolo9k_sub2/ — a copy of yolo9k_sub plus negNNNN.jpg images
with EMPTY .txt label files (ultralytics treats an empty label as a
background image). Writes data.yaml pointing at the mix.
"""
from __future__ import annotations

import sys
import os
from pathlib import Path

import cv2
import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[2]
SRC = REPO_ROOT / "data" / "cv" / "yolo9k_sub"     # cracked subset
OUT = REPO_ROOT / "data" / "cv" / "yolo9k_sub2"    # cracked + negatives
IMG_H = IMG_W = 400
PATCH = 256
MAX_CRACK_FRAC = 0.005    # a patch with <0.5% crack is "clean"
QUADRANTS = [(0, 0), (IMG_W - PATCH, 0), (0, IMG_H - PATCH),
             (IMG_W - PATCH, IMG_H - PATCH)]


def crack_mask(label_path: Path, h: int = IMG_H, w: int = IMG_W) -> np.ndarray:
    """Rasterize a YOLO-seg label file back to a binary 400x400 mask."""
    m = np.zeros((h, w), np.uint8)
    if not label_path.exists():
        return m
    for line in label_path.read_text(encoding="utf-8").splitlines():
        parts = line.split()
        if len(parts) < 9:
            continue
        xy = np.array([float(v) for v in parts[1:]]).reshape(-1, 2)
        xy[:, 0] *= w
        xy[:, 1] *= h
        cv2.fillPoly(m, [xy.astype(np.int32)], 255)
    return m


def clean_quadrant(mask: np.ndarray) -> tuple[int, int] | None:
    """Return top-left (x, y) of a clean 256x256 quadrant, or None."""
    for (x0, y0) in QUADRANTS:
        if (mask[y0:y0 + PATCH, x0:x0 + PATCH] > 0).mean() < MAX_CRACK_FRAC:
            return x0, y0
    return None


def build_split(split: str) -> tuple[int, int]:
    img_src = SRC / "images" / split
    lbl_src = SRC / "labels" / split
    for sub in ("images", "labels"):
        (OUT / sub / split).mkdir(parents=True, exist_ok=True)

    # 1) hardlink the cracked positives (already done by yolo9k_sub)
    n_pos = 0
    for im in sorted(img_src.glob("*.jpg")):
        lbl = lbl_src / (im.stem + ".txt")
        if not lbl.exists():
            continue
        for src, dst in ((im, OUT / "images" / split / im.name),
                         (lbl, OUT / "labels" / split / lbl.name)):
            if not dst.exists():
                # ROADMAP line 66: hardlinks fail on some filesystems (cross-
                # volume, FAT, APFS/ReFS) — fall back to a real copy.
                try:
                    os.link(src, dst)
                except OSError:
                    import shutil
                    shutil.copy2(src, dst)
        n_pos += 1

    # 2) crop a clean quadrant from each image whose label allows it
    n_neg = 0
    for im in sorted(img_src.glob("*.jpg")):
        m = crack_mask(lbl_src / (im.stem + ".txt"))
        quad = clean_quadrant(m)
        if quad is None:
            continue
        img = cv2.imread(str(im))
        if img is None:
            continue
        x0, y0 = quad
        crop = img[y0:y0 + PATCH, x0:x0 + PATCH]
        name = f"neg{n_neg:05d}"
        cv2.imwrite(str(OUT / "images" / split / f"{name}.jpg"), crop)
        (OUT / "labels" / split / f"{name}.txt").write_text("", encoding="utf-8")
        n_neg += 1
    print(f"  [{split}] positives={n_pos} negatives={n_neg}")
    return n_pos, n_neg


def main() -> int:
    if not (SRC / "images" / "train").exists():
        print(f"ERROR: {SRC} missing — run the subset build first "
              "(1/3 sample of yolo9k, see train_yolo workflow).", file=sys.stderr)
        return 1
    print(f"building yolo9k_sub2 (positives + clean-negative crops) at {OUT}")
    t_pos, t_neg = build_split("train")
    v_pos, v_neg = build_split("val")
    yaml = (
        "# YOLO-seg dataset: 1/3 CrackSeg9k subset + crack-free negative "
        "crops (100% CC0).\n"
        "# Negatives teach 'plain concrete = no crack' (CrackSeg9k has none).\n"
        "# Generated by models/cv/prep_negatives.py from yolo9k_sub.\n"
        f"path: {str(OUT)}\n"
        "train: images/train\n"
        "val: images/val\n"
        "names:\n"
        "  0: crack\n"
    )
    (OUT / "data.yaml").write_text(yaml, encoding="utf-8")
    print(f"\nDONE: train {t_pos}+{t_neg} | val {v_pos}+{v_neg}")
    print(f"data.yaml at {OUT / 'data.yaml'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
