"""Shared real-Z24 window loader for the trained-ML gates (TEST-F3).

Serves real Z24 benchmark windows (channels 6/7/8, 1024-sample non-overlapping)
to `test_trained_path.py` §4 and `test_deconfounding.py` LEG C from EITHER the
full benchmark (`data/z24/inputs.npy`, 991 MB, gitignored) OR the committed
fixture (`data/z24/fixture/*.npy`, ~3 MB, regenerated by
`scripts/make_z24_fixture.py`).  The fixture is a deterministic per-label sample
of the SAME benchmark, so a fresh clone / CI exercises real Z24 evidence
instead of silently skipping (the TEST-F3 gap).

The envelope-fit split is load-bearing: the trained envelope is built from
label-0 healthy windows only, so label 0 stays ~0 while healthy labels 1 and 6
deviate like damage (measured max ~0.31 / ~0.37 — documented state-confounding,
pinned in `test_deconfounding.py` LEG C).  Do NOT merge healthy1 into the
warm-up: the gates assert the detector's ACTUAL behavior, not a fixed version
of it.

Returned dict: {'hw0','hw1','hw6','dw' (float64 window arrays),
'source': 'full'|'fixture', 'present': bool}.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[2]  # repo root (backend/tests/ -> .. -> ..)
Z24 = ROOT / "data" / "z24" / "inputs.npy"
Z24_LABELS = Z24.with_name("labels.npy")
FIXTURE = ROOT / "data" / "z24" / "fixture"

W = 1024
CHANNELS = (6, 7, 8)
# Segments sampled per label.  12 -> 180 windows per label (12 segs x 3 ch x 5);
# the gates use hw0[:5] warm-up + hw0[5:45] / hw1[:40] / hw6[:40] / dw[:40].
SEGMAX = 12
DAMAGED_LABELS = [2, 3, 4, 5, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]

_FIXTURE_FILES = ("healthy0.npy", "healthy1.npy", "label6.npy", "damaged.npy")


def has_full() -> bool:
    return bool(Z24.exists() and Z24_LABELS.exists())


def has_fixture() -> bool:
    return all((FIXTURE / f).exists() for f in _FIXTURE_FILES)


def _windows_from_full(labels, segmax=SEGMAX) -> np.ndarray:
    """Label-order window iteration (matches the pre-fixture gate behavior, so
    the measured full-data numbers are preserved exactly)."""
    arr = np.load(Z24, mmap_mode="r")
    lab = np.load(Z24_LABELS).ravel()
    out = []
    for target in labels:
        idx = np.where(lab == target)[0][:segmax]
        for s in idx:
            for c in CHANNELS:
                row = arr[s, c]
                for i in range(0, 6000 - W + 1, W):
                    out.append(row[i:i + W])
    return np.stack(out).astype(np.float64)


def load_windows() -> dict:
    """Real Z24 windows, preferring the full benchmark and falling back to the
    committed fixture.  Returns source='full' | 'fixture' | None (absent)."""
    if has_full():
        return {
            "hw0": _windows_from_full([0]),
            "hw1": _windows_from_full([1]),
            "hw6": _windows_from_full([6]),
            "dw": _windows_from_full(DAMAGED_LABELS),
            "source": "full",
            "present": True,
        }
    if has_fixture():
        return {
            "hw0": np.load(FIXTURE / "healthy0.npy").astype(np.float64),
            "hw1": np.load(FIXTURE / "healthy1.npy").astype(np.float64),
            "hw6": np.load(FIXTURE / "label6.npy").astype(np.float64),
            "dw": np.load(FIXTURE / "damaged.npy").astype(np.float64),
            "source": "fixture",
            "present": True,
        }
    return {"hw0": None, "hw1": None, "hw6": None, "dw": None,
            "source": None, "present": False}
